# Generated by Django 3.2 on 2021-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
    ]
